---
name: enos_fmt

on:
  pull_request:
    paths:
      - enos/**

jobs:
  fmt_check:
    # Only run this workflow on pull requests from hashicorp/vault branches
    # as we need secrets to install enos.
    if: "! github.event.pull_request.head.repo.fork"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_wrapper: false
      - uses: hashicorp/action-setup-enos@8a30c335de1c4ce4d3afb6578db6352e908ccce8 # v1.21
        with:
          github-token: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
      - name: check formatting
        working-directory: ./enos
        run: make check-fmt
