# This workflow checks that there is either a 'pr/no-milestone' label applied to a PR
# or there is a milestone associated with a PR

name: Check Milestone

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]
    # Runs on PRs to main and release branches
    branches:
      - main
      - release/**
  issues:
    types: [milestoned, demilestoned]

jobs:
  # checks that a milestone entry is present for a PR
  milestone-check:
    # If there is a `pr/no-milestone` label we ignore this check
    if: "! ( contains(github.event.pull_request.labels.*.name, 'pr/no-milestone') || ( github.event.name == 'labeled' && github.event.label == 'pr/no-milestone' ) )"
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
        with:
          egress-policy: audit

      - name: Checkout Actions
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: "grafana/grafana-github-actions"
          path: ./actions
          ref: main
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run PR Checks
        uses: ./actions/pr-checks
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          configPath: configs/milestone-check
